services:
  vaultwarden:
    container_name: vaultwarden-${SITE_NAME}
    image: vaultwarden/server:1.32.7-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - vaultwarden_data:/data
    ports:
      - "127.0.0.1:${PORT_MAIN}:80"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:80/alive || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 6
      start_period: 30s
    networks:
      - xcloud-network

volumes:
  vaultwarden_data:

networks:
  xcloud-network:
    driver: bridge
